### ISSUE TITLE
about infer output

### ISSUE THREAD

**Issue by WSTao** [hitfee01/Yolo3D#3]
On line 163 of the train.py file, the model output is only one output(pred = model(imgs)), but on line 105 of the test.py file, why are there two outputs(inf_out, train_out = model(img)). Where does the extra output increase?

**Comment by hitfeelee** [comment]
In test, inf_out is used for calculating mAp , and train_out for loss, the both is used for evaluating best model. Of cause, you can keep model to output train_out, and implement function inference outside the model

**Comment by WSTao** [comment]
I got it, Thx!
